### ISSUE TITLE
Custom teardown

### ISSUE THREAD

**Issue by phihag** [boxine/pentf#121]
(Originally reported by Johann) It would be nice to be able to register custom tearDown functions. These should be executed after the main `run` has errored, but before the locks on objects have been returned.

`-k` should imply disabling these tearDowns for failed tests.

**Comment by marvinhagemeister** [comment]
We could add something like that, but I'm curious if a simple `try/finally´ is just as good:

```js
async function run() {
  try {
    throw new Error("fail");
  } finally {
    // teardown logic
  }
}
```

> `-k` should imply disabling these tearDowns for failed tests.

Hm I probably don't have enough context here. What could be a use case for that where one wouldn't want to run the teardown code?

**Comment by phihag** [comment]
@marvinhagemeister Johann wants to delete (almost) all user accounts that were created.

try .. finally would work, but it would bloat the tests by a lot.

When `-k` is given, the tester can interact with the browsers after a failure, for example use the devtools, or make a code change and then manually retest. In this case, we do not want to delete user accounts.

**Comment by marvinhagemeister** [comment]
Whilst working on the locking system and trying to switch to pentf in an unannounced project I've been pondering a lot about this. The way I see it we have several types of "resources" that want to run cleanup logic after a test is done, regardless of if it failed or not. I didn't consider the `keep_open` use case before, but I'm starting to thing that I found something which would satisfy all our needs.

Viewed from afar we have several types of resources and devs may have even more depending on the project:

| Type | Setup | Shutdown |
|---|---|---|
| browser instance/page | Open browser window | shutdown browser pages + all windows |
| locking | acquire lock | release all owned locks |
| (userspace) | custom setup code | custom teardown logic |

In a nutshell we have a bunch of cleanup functions we want to call. We currently call browser shutdown functions and locking at different times and I feel like there is potential to find a generic solution to this. Other frameworks usually have some sort of `beforeEach` and `afterEach` lifecycle hooks that are invoked before and after each test case respectively:

```js
// Jest example
describe('example', () => {
  // BAD: resource leaks across tests
  let resource;

  beforeEach(() => {
    resource = setup();
  });

  afterEach(() => {
    teardown(resource);
  });

  test('foo', () => {
    // beforeEach callback will be run before this function
    doSomeTest();
    // afterEach callback will fire after this function
  });
});
```

Mocha, jasmine, ava and other JavaScript frameworks are pretty similar and mostly differ in naming. The problem with that is that the resource is shared via an implicit closure. Whilst this is easy to use and very beginner-friendly it causes havoc for parallelism. When there are multiple test cases running at the same time, there will be no guarantee that the `resource` variable has a consistent state. If test 1 is still running but test 2 already finished it will tear down the resource, even though test 1 is using it.

Just to confirm that I'm not missing something, I've checked jest's code for their runner. They only do parallelism at the suite level, meaning all files are run in parallel whereas individual test cases aren't.

We currently don't support multiple test cases in the same file, but I'd not rule that feature out for the future. So I'm trying to find a way to set up and teardown resources that doesn't rely on scope sharing of variables and reduces that source of error.

There is of course the manual way as described in my previous post of littering a `try/finally` into every test case, but I fully agree with your argument of this being overly verbose. It becomes even more problematic in case a user forgets to wrap the code with a `try/finally`. Then we'd be leaking resources which is a big no-no!

One of the youngest test frameworks [uvu](https://github.com/lukeed/uvu) went with passing an explicit `context` argument around which reminds me a lot of our `config` one. Ours mostly contains configuration code but got more and more stateful over time and the name `config` doesn't really do it justices anymore. I can totally see why that happened and I'm really curious if we benefit from refactoring that in the future!

But back to `uvu`. They don't support any form of concurrency yet, but consciously .

```js
const mySuite = suite('My cool suite');

mySuite.before(context => {
  context.resource = setup();
});

mySuite.after(context => {
  teardown(context.resource);
});

mySuite.test('my cool test', context => {
  console.log(context.resource);
});
```

This is definitely going into the right direction, but I feel like this isn't _it_. There must be a more a elegant solution out there. Maybe I'm to much used to other writing styles, but for me the disconnect between the test and setup code itself is a bit much.

## A possible solution?

So I've been pondering the past days about this problem and I think I've come across something that's easier and more straightforward to understand:

```js
async function run(context) {
  const resource = setup(context);
  // ...
}
```

And setup would be defined like this:

```js
function setup(context) {
  const resource = doSomething();
  // Setup automatically attaches a callback function to
  // the current task, that's called by the runner when the
  // test is finished.
  context.cleanup_hooks.push(() => teardown(resource));
  return resource;
}
```

The nice thing about this is that we still retain the ease of use of variable passing instead of having to push our resource onto a random object just to pull it off again. The advantage of this approach is that our runner code would get even simpler. Currently it roughly looks like this:

```js
try {
  run_task();
} finally {
  if (!config.keep_open) {
    closeBrowserPages();
    locks.release();
  }
}
```

With the above idea we can remove browser or lock specific code out of the runner:

```js
try {
  run_task();
} finally {
  if (!config.keep_open) {
    task.cleanup_hooks.forEach(hook => hook());
  }
}
```

On top of that this would allow us to add future cleanup logic without the need to hard code that into the runner. The biggest beneficiary is the user though. With this he could create custom setup and teardown logic easily and ensure that it's called even if the test fails.

**Comment by marvinhagemeister** [comment]
Another thing I just stumbled upon with `--keep_open`: If we add this flag to a run and every test passes, the runner will never exit. We should probably check if a browser window is still visible and if there isn't we should shut down.
