### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by marvinhagemeister** [boxine/pentf#123]
I accidentally pushed into it this morning :grimacing:

**Comment by phihag** [comment]
Fortunately, you can easily revert this on GitHub.

At the moment, I do push on master branches for releases. How would that work with a protected master? Since it involves modifying the `package.json`, I really don't see a way around it.

And releases seem like a lot of toil already, so I wouldn't want to make them a two-man operation.

**Comment by marvinhagemeister** [comment]
Alright, that's a fair point 👍

**Comment by phihag** [comment]
I have set up the master branch protection now, but excepted myself, to be used for release commits only.
